import { StyleSheet } from "react-native";

import { colors, spacing } from "@/constants/theme";

export const horoscopeStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.cream },
  header: {
    minHeight: 56,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
    paddingBottom: spacing.xs,
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm
  },
  headerAction: { width: 86, marginLeft: -8 },
  headerTitle: { flex: 1, color: colors.ink, fontWeight: "800", textAlign: "center" },
  content: { paddingBottom: spacing.xl, gap: spacing.lg },
  hero: { paddingTop: spacing.xl, paddingBottom: spacing.xl, gap: spacing.xl },
  signRail: { flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between", rowGap: spacing.md, paddingHorizontal: spacing.md },
  signButton: { width: "15.5%", alignItems: "center", gap: spacing.xs },
  signIconShell: { width: 48, height: 48, borderRadius: 8, backgroundColor: "rgba(255,255,255,0.08)", alignItems: "center", justifyContent: "center" },
  signIconShellActive: { borderWidth: 2, borderColor: colors.gold, backgroundColor: "rgba(255,255,255,0.16)" },
  signIcon: { width: 34, height: 34, borderRadius: 17, alignItems: "center", justifyContent: "center" },
  signLabel: { color: "#d9d1b8", fontSize: 9, fontWeight: "800", textTransform: "uppercase", textAlign: "center" },
  signLabelActive: { color: "#fff7d4" },
  heroCopy: { paddingHorizontal: spacing.xl },
  heroTitle: { color: "#ff666d", fontSize: 32, lineHeight: 38, fontWeight: "900", flexWrap: "wrap" },
  heroTitleSoft: { color: "#9fc18f" },
  heroSubtitle: { color: "#efe4c6", fontSize: 16, marginTop: spacing.xs, fontWeight: "700" },
  controls: { paddingHorizontal: spacing.lg, gap: spacing.sm, paddingTop:10 },
  controlTitle: { color: colors.ink, fontWeight: "800", lineHeight: 22 },
  dropdown: {
    minHeight: 50,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.md,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between"
  },
  dropdownText: { flex: 1, minWidth: 0, color: colors.ink, fontSize: 15, lineHeight: 19, fontWeight: "700" },
  tabs: {
    marginHorizontal: spacing.lg,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: 3,
    flexDirection: "row"
  },
  tab: { flex: 1, minHeight: 40, borderRadius: 6, alignItems: "center", justifyContent: "center" },
  tabActive: { backgroundColor: "#fff0c1" },
  tabDisabled: { opacity: 0.4 },
  tabText: { color: colors.cocoa, fontWeight: "800" },
  tabTextActive: { color: colors.ink },
  tabTextDisabled: { color: "#9d8d60" },
  panel: { marginHorizontal: spacing.lg, gap: spacing.md },
  panelTitle: { color: colors.ink, fontWeight: "900", lineHeight: 28 },
  meta: { color: colors.cocoa },
  readingCard: { borderRadius: 8, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, padding: spacing.lg, gap: spacing.sm },
  cardTitle: { color: colors.amber, fontWeight: "800" },
  bodyText: { color: colors.ink, lineHeight: 22 },
  extraCard: { borderRadius: 8, borderWidth: 1, borderColor: colors.border, backgroundColor: "#fffaf0", padding: spacing.lg, gap: spacing.md },
  colorRow: { flexDirection: "row", flexWrap: "wrap", gap: spacing.md },
  colorItem: { flexDirection: "row", alignItems: "center", gap: spacing.sm },
  colorSwatch: { width: 24, height: 24, borderRadius: 12, borderWidth: 1, borderColor: colors.border },
  percentRow: { flexDirection: "row", alignItems: "center", gap: spacing.sm },
  percentLabel: { flex: 0.9, minWidth: 82, color: colors.cocoa, fontWeight: "700", lineHeight: 18 },
  percentTrack: { flex: 1, height: 8, borderRadius: 4, backgroundColor: "#f0dfb3", overflow: "hidden" },
  percentFill: { height: "100%", borderRadius: 4, backgroundColor: colors.success },
  percentValue: { width: 42, color: colors.ink, textAlign: "right", fontWeight: "800" }
});
