import { StyleSheet } from "react-native";

import { colors, spacing } from "@/constants/theme";

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#f8f7f2" },
  header: {
    minHeight: 58,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: spacing.md,
    gap: spacing.sm
  },
  headerTitle: { flex: 1, minWidth: 0, color: colors.ink, fontWeight: "700", fontSize: 15, lineHeight: 19, textAlign: "center" },
  headerSpacer: { width: 70 },
  scroll: { flex: 1 },
  content: { minHeight: "100%", alignSelf: "center", width: "100%", maxWidth: 420, backgroundColor: "#ffffc9", padding: spacing.lg, paddingBottom: 104 },
  panel: { paddingTop: spacing.lg, gap: spacing.lg },
  formStack: { flexDirection: "row", alignItems: "flex-start", borderWidth: 1.2, borderColor: "#111", borderRadius: 5, backgroundColor: "#fff" },
  fieldIcon: { width: 36, minHeight: 31, alignItems: "center", justifyContent: "center" },
  input: { flex: 1, minHeight: 31, paddingVertical: 5, paddingHorizontal: 0, color: "#111", fontFamily: "serif", fontSize: 16 },
  dateSelect: { flex: 1, minHeight: 35, justifyContent: "center", paddingRight: spacing.sm },
  dateSelectText: { color: "#111", fontFamily: "serif", fontSize: 16 },
  placeholderText: { color: "#9c9c9c" },
  genderRow: { flexDirection: "row", gap: spacing.sm },
  genderBtn: { flex: 1, minHeight: 40, borderRadius: 5, borderWidth: 1, borderColor: "#111", alignItems: "center", justifyContent: "center", backgroundColor: "#fff", paddingHorizontal: 4, paddingVertical: 3 },
  genderBtnActive: { backgroundColor: "#c7efc8", borderColor: "#34a853" },
  genderText: { color: "#111", fontSize: 13, lineHeight: 16, fontWeight: "700", textAlign: "center" },
  genderTextActive: { color: "#145c24", fontWeight: "900" },
  calculationSelect: { flex: 1 },
  calculationTrigger: { minHeight: 35, flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingRight: spacing.sm },
  calculationValue: { fontFamily: "serif", fontSize: 16, color: "#111" },
  calculationMenu: { borderTopWidth: 1, borderTopColor: "#111" },
  calculationOption: { minHeight: 34, justifyContent: "center", paddingRight: spacing.sm, borderTopWidth: 1, borderTopColor: "#e5e5e5" },
  calculationOptionActive: { backgroundColor: "#c7efc8" },
  calculationOptionText: { fontFamily: "serif", fontSize: 15, color: "#111" },
  calculationOptionTextActive: { color: "#145c24", fontWeight: "900" },
  validation: { color: colors.danger, fontSize: 12, fontWeight: "800", lineHeight: 17 },
  actionRow: { flexDirection: "row", gap: spacing.sm },
  clearBtn: { minWidth: 104, minHeight: 38, borderRadius: 5, borderWidth: 1, borderColor: "#111", backgroundColor: "#fff", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 5, paddingHorizontal: spacing.sm, paddingVertical: 3 },
  clearText: { fontFamily: "serif", fontWeight: "900", color: "#111", fontSize: 15, lineHeight: 18, textAlign: "center" },
  submitBtn: { minHeight: 38, borderRadius: 5, borderWidth: 1, borderColor: "#111", backgroundColor: "#ffcf28", alignItems: "center", justifyContent: "center", paddingHorizontal: spacing.sm, paddingVertical: 3 },
  submitBtnFlex: { flex: 1 },
  submitText: { fontFamily: "serif", fontWeight: "900", color: "#111", fontSize: 16, lineHeight: 19, textAlign: "center" },
  resultContent: { alignSelf: "center", width: "100%", maxWidth: 420, backgroundColor: "#ffffc9", padding: spacing.lg, paddingBottom: 104, gap: spacing.lg },
  gridIntro: { minHeight: 80, borderRadius: 8, backgroundColor: "#f8fff6", paddingHorizontal: spacing.sm, paddingVertical: spacing.md, flexDirection: "column", gap: spacing.md, shadowColor: "#0d5a1d", shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.18, shadowRadius: 5, elevation: 4 },
  gridIntroTitleWrap: {  width: "100%", borderRadius: 6, backgroundColor: "#bff2c6", alignItems: "center", justifyContent: "center", paddingHorizontal: spacing.md, paddingVertical: 6 },
  gridIntroTitle: { color: "#145c24", fontSize: 18, lineHeight: 32, fontWeight: "900", textAlign: "center", includeFontPadding: true },
  gridIntroDescription: { flex: 1, width: "100%", color: "#243727", fontSize: 15, lineHeight: 25, fontWeight: "800", textAlign: "center", includeFontPadding: true },
  sectionLabel: { alignSelf: "center", width: "100%", minHeight: 62, borderRadius: 5, borderWidth: 1, borderColor: "#39a853", backgroundColor: "#bff2c6", alignItems: "center", justifyContent: "center", paddingHorizontal: spacing.md, paddingVertical: 8 },
  sectionLabelText: { color: "#145c24", fontSize: 18, lineHeight: 28, fontWeight: "900", textAlign: "center", includeFontPadding: true },
  loShuGrid: { alignSelf: "center", width: 204, height: 156, flexDirection: "row", flexWrap: "wrap", borderRadius: 10, backgroundColor: "#fff", padding: 6, gap: 4, shadowColor: "#0d3440", shadowOffset: { width: 0, height: 5 }, shadowOpacity: 0.22, shadowRadius: 8, elevation: 6 },
  loShuCell: { width: 61.33, height: 45.33, borderRadius: 7, backgroundColor: "#f8fff6", alignItems: "center", justifyContent: "center", shadowColor: "#0d3440", shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.08, shadowRadius: 2, elevation: 1 },
  loShuText: { fontSize: 18, fontWeight: "900", color: "#111" },
  cardGrid: { flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between", rowGap: 10, columnGap: 10 },
  yearCards: { flexDirection: "row", gap: spacing.sm },
  numberCard: { flexGrow: 1, flexBasis: "31%", minHeight: 96, borderRadius: 8, borderWidth: 2, borderColor: "#68ad62", backgroundColor: "#fff", alignItems: "center", justifyContent: "center", paddingHorizontal: 6, paddingVertical: 8, shadowColor: "#000", shadowOpacity: 0.25, shadowRadius: 2, elevation: 2 },
  numberLabel: { color: "#777", fontSize: 12, lineHeight: 20, fontWeight: "900", textAlign: "center", includeFontPadding: true },
  numberValue: { color: "#136a28", fontSize: 24, lineHeight: 28, fontWeight: "900" },
  numberNote: { color: "#777", fontSize: 10, lineHeight: 16, fontWeight: "800", textAlign: "center", includeFontPadding: true },
  detailButton: { minHeight: 68, borderRadius: 10, borderWidth: 1.5, borderColor: "#32b248", backgroundColor: "#f8fff6", paddingHorizontal: spacing.md, paddingVertical: spacing.sm, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing.sm, shadowColor: "#0d5a1d", shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.24, shadowRadius: 5, elevation: 5 },
  detailButtonCopy: { flex: 1 },
  detailButtonTitle: { color: "#0b5719", fontSize: 15, lineHeight: 19, fontWeight: "900" },
  detailButtonSubtitle: { color: "#36543a", fontSize: 12, lineHeight: 16, fontWeight: "800", marginTop: 3 },
  detailButtonArrow: { width: 38, height: 38, borderRadius: 19, backgroundColor: "#1d8d31", alignItems: "center", justifyContent: "center", shadowColor: "#0d5a1d", shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.24, shadowRadius: 3, elevation: 3 },
  repetitionSection: { borderRadius: 8, borderWidth: 1.5, borderColor: "#b5d7ff", backgroundColor: "#eaf5ff", padding: spacing.md, gap: spacing.md, shadowColor: "#0b3a78", shadowOpacity: 0.14, shadowRadius: 5, elevation: 3 },
  repetitionHero: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing.md },
  repetitionHeroCopy: { flex: 1 },
  repetitionKicker: { color: "#1167df", fontSize: 15, lineHeight: 20, fontWeight: "900" },
  repetitionTitle: { color: "#061b4f", fontSize: 24, lineHeight: 30, fontWeight: "900", marginTop: 3 },
  repetitionGrid: { width: 132, height: 132, flexDirection: "row", flexWrap: "wrap", borderRadius: 8, backgroundColor: "#fff", padding: 5, gap: 3, shadowColor: "#0b3a78", shadowOpacity: 0.2, shadowRadius: 6, elevation: 5 },
  repetitionGridCell: { width: 38, height: 38, borderRadius: 5, borderWidth: 1, borderColor: "#edf2ff", alignItems: "center", justifyContent: "center", backgroundColor: "#fff", paddingVertical: 2 },
  repetitionGridCellActive: { backgroundColor: "#d8ecff" },
  repetitionGridCellMissing: { backgroundColor: "#f1f1f1" },
  repetitionGridNumber: { color: "#061b4f", fontSize: 18, lineHeight: 22, fontWeight: "900", textAlign: "center", paddingHorizontal: 2 },
  repetitionGridNumberMissing: { color: "#777", fontSize: 16, lineHeight: 18 },
  repetitionGridMissingLabel: { color: "#777", fontSize: 7, lineHeight: 9, fontWeight: "900", textAlign: "center" },
  repetitionGridNumberMany: { color: "#d71920" },
  repetitionCards: { gap: spacing.sm },
  repetitionCard: { minHeight: 104, borderRadius: 8, backgroundColor: "#fff", padding: spacing.md, flexDirection: "row", alignItems: "flex-start", gap: spacing.md, shadowColor: "#0b3a78", shadowOpacity: 0.12, shadowRadius: 4, elevation: 2 },
  repetitionIcon: { width: 54, height: 54, borderRadius: 27, backgroundColor: "#e1f0ff", alignItems: "center", justifyContent: "center" },
  repetitionCopy: { flex: 1 },
  repetitionCardTitle: { color: "#061b4f", fontSize: 18, lineHeight: 23, fontWeight: "900" },
  repetitionTitleMissing: { color: "#777" },
  repetitionTitleOnce: { color: "#111" },
  repetitionTitleTwice: { color: "#d9a300" },
  repetitionTitleMany: { color: "#d71920" },
  repetitionCardText: { color: "#111", fontSize: 13, lineHeight: 20, marginTop: 5 },
  repetitionNoteRow: { flexDirection: "row", alignItems: "flex-start", justifyContent: "center", gap: spacing.sm, paddingHorizontal: spacing.sm },
  repetitionNote: { flex: 1, color: "#111", fontSize: 12, lineHeight: 18, fontWeight: "700" },
  relationTable: {backgroundColor: "#cfcfcf", borderWidth: 1.5, borderTopColor: "#f3fff0", borderLeftColor: "#f3fff0", borderRightColor: "#6d806d", borderBottomColor: "#6d806d" },
  relationHeader: { flexDirection: "row", minHeight: 58 },
  relationHeadText: { textAlign: "center", textAlignVertical: "center", fontFamily: "serif", fontSize: 10, fontWeight: "900", color: "#111", backgroundColor: "#a9d4ad", borderWidth: 1.5, borderTopColor: "#eaffdf", borderLeftColor: "#eaffdf", borderRightColor: "#5f7a63", borderBottomColor: "#5f7a63" },
  relationNumberHead: { width: 90, fontSize: 12 },
  relationFriendHead: { width: 76 },
  relationEnemyHead: { width: 80 },
  relationNeutralHead: { width: 80 },
  relationRow: { flexDirection: "row", minHeight: 52 },
  relationLabel: { textAlign: "center", textAlignVertical: "center", fontFamily: "serif", fontSize: 8, fontWeight: "900", color: "#174f1d", backgroundColor: "#b8ddb9", borderWidth: 1.5, borderTopColor: "#eaffdf", borderLeftColor: "#eaffdf", borderRightColor: "#5f7a63", borderBottomColor: "#5f7a63" },
  relationNameCell: { width: 60 },
  relationCell: { textAlign: "center", textAlignVertical: "center", fontSize: 13, fontWeight: "900", color: "#111", backgroundColor: "#d8d8d8", borderWidth: 1.5, borderTopColor: "#f8f8f8", borderLeftColor: "#f8f8f8", borderRightColor: "#858585", borderBottomColor: "#858585" },
  relationNumberCell: { width: 30 },
  relationFriendCell: { width: 76 },
  relationEnemyCell: { width: 80 },
  relationNeutralCell: { width: 80 },
  friendText: { color: "#00a84f" },
  enemyText: { color: "#f00" },
  neutralText: { color: "#858585" },
  relationFoot: { flexDirection: "row", minHeight: 56 },
  relationFootLabel: { width: 90, fontSize: 10, lineHeight: 15 },
  relationFootValue: { width: 235, textAlign: "center", textAlignVertical: "center", color: "#111", fontSize: 14, fontWeight: "900", backgroundColor: "#d8d8d8", borderWidth: 1.5, borderTopColor: "#f8f8f8", borderLeftColor: "#f8f8f8", borderRightColor: "#858585", borderBottomColor: "#858585" },
  effectsBox: { borderRadius: 8, backgroundColor: "#fffde5", padding: spacing.sm, gap: spacing.sm, shadowColor: "#0d3440", shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.16, shadowRadius: 6, elevation: 4 },
  combinationBadge: { alignSelf: "flex-start", minHeight: 31, borderRadius: 5, backgroundColor: "#fff", flexDirection: "row", alignItems: "center", overflow: "hidden", shadowColor: "#0d3440", shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.14, shadowRadius: 4, elevation: 2 },
  combinationLabel: { paddingHorizontal: 8, paddingVertical: 3, color: "#111", fontSize: 12, lineHeight: 18, fontWeight: "900" },
  combinationValue: { minHeight: 31, paddingHorizontal: 10, paddingVertical: 3, color: "#145c24", backgroundColor: "#bff2c6", textAlignVertical: "center", fontSize: 14, lineHeight: 20, fontWeight: "900" },
  effectPanels: { gap: spacing.sm },
  effectPanel: { minHeight: 100, flexDirection: "row", alignItems: "flex-start", gap: spacing.sm, borderRadius: 8, backgroundColor: "#fff", padding: spacing.md, shadowColor: "#0b3a78", shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.14, shadowRadius: 5, elevation: 3 },
  effectIcon: { width: 38, height: 38, borderRadius: 19, alignItems: "center", justifyContent: "center" },
  effectCopy: { flex: 1 },
  effectTitle: { fontSize: 22, lineHeight: 32, fontWeight: "900" },
  effectText: { color: "#111", fontSize: 15, lineHeight: 24, paddingVertical: 2 },
  yearInputs: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm, alignItems: "center" },
  yearInput: { flexGrow: 1, flexBasis: "30%", minHeight: 40, borderWidth: 1, borderColor: "#111", borderRadius: 5, backgroundColor: "#fff", paddingHorizontal: 8, paddingVertical: 3, color: "#111", fontSize: 13, lineHeight: 18, textAlignVertical: "center" },
  smallBtn: { minHeight: 40, paddingHorizontal: spacing.md, paddingVertical: 3, borderRadius: 5, borderWidth: 1, borderColor: "#111", backgroundColor: "#ffcf28", alignItems: "center", justifyContent: "center" },
  smallBtnText: { color: "#111", fontWeight: "900", lineHeight: 17, textAlign: "center" },
  matrixTable: { borderTopWidth: 1, borderLeftWidth: 1, borderColor: "#111", backgroundColor: "#fff" },
  matrixTopHeader: { flexDirection: "row", backgroundColor: "#ffd95d" },
  matrixMonthHeader: { flexDirection: "row" },
  matrixRow: { flexDirection: "row" },
  matrixHeadCell: { width: 48, minHeight: 34, textAlign: "center", textAlignVertical: "center", borderRightWidth: 1, borderBottomWidth: 1, borderColor: "#111", fontSize: 12, fontWeight: "900", color: "#111" },
  matrixTallHead: { minHeight: 68, borderBottomWidth: 0 },
  matrixHeadSpacer: { minHeight: 34, borderRightWidth: 1, borderBottomWidth: 1, borderColor: "#111", backgroundColor: "#ffd95d" },
  matrixMonthGroup: { width: 576, minHeight: 34, textAlign: "center", textAlignVertical: "center", borderRightWidth: 1, borderBottomWidth: 1, borderColor: "#111", fontFamily: "serif", fontSize: 14, fontWeight: "900", color: "#111" },
  matrixCell: { width: 48, minHeight: 34, textAlign: "center", textAlignVertical: "center", borderRightWidth: 1, borderBottomWidth: 1, borderColor: "#111", fontSize: 15, fontWeight: "800", color: "#111" },
  matrixYear: { width: 54 },
  matrixPersonal: { width: 86 },
  matrixPersonalValueCell: { alignItems: "center", justifyContent: "center" },
  matrixPersonalYearText: { fontSize: 15, lineHeight: 20, fontWeight: "900", textAlign: "center" },
  matrixPersonalYearFirst: { color: "#d71920", fontWeight: "900" },
  matrixPersonalYearSlash: { color: "#111", fontWeight: "900" },
  matrixPersonalYearLast: { color: "#148f36", fontWeight: "900" },
  readingBox: { borderWidth: 2, borderColor: "#0d3440", backgroundColor: "#fffde5", padding: spacing.sm },
  readingTitle: { fontFamily: "serif", color: "#111", fontSize: 25, lineHeight: 30, fontWeight: "900" },
  readingText: { fontFamily: "serif", color: "#111", fontSize: 16, lineHeight: 21 },
  detailContent: { alignSelf: "center", width: "100%", maxWidth: 420, backgroundColor: "#ffffc9", padding: spacing.lg, paddingBottom: 104, gap: spacing.lg },
  detailContainer: { paddingHorizontal: spacing.lg, paddingTop: spacing.lg, paddingBottom: spacing.sm, backgroundColor: "#ffffc9" },
  detailTabs: { flexDirection: "row", borderWidth: 1, borderColor: "#34a853", borderRadius: 7, backgroundColor: "#fff", padding: 3, shadowColor: "#000", shadowOpacity: 0.14, shadowRadius: 3, elevation: 2 },
  detailTab: { flex: 1, minHeight: 44, borderRadius: 5, alignItems: "center", justifyContent: "center", paddingHorizontal: 4, paddingVertical: 3 },
  detailTabActive: { backgroundColor: "#bff2c6" },
  detailTabText: { width: "100%", color: "#424242", fontSize: 13, lineHeight: 16, textAlign: "center", fontWeight: "900" },
  detailTabTextActive: { color: "#145c24" },
  detailStack: { gap: spacing.lg },
  detailSummary: { borderRadius: 7, borderWidth: 1, borderColor: "#39a853", backgroundColor: "#fff", padding: spacing.md, shadowColor: "#000", shadowOpacity: 0.16, shadowRadius: 3, elevation: 2 },
  detailSummaryNumber: { color: "#145c24", fontSize: 18, lineHeight: 28, fontWeight: "900" },
  detailSummaryText: { color: "#111", fontSize: 13, lineHeight: 21, fontWeight: "700", marginTop: 2 },
  detailCard: { borderWidth: 1, borderRadius:7, borderColor: "#39d34a", backgroundColor: "#fff", paddingHorizontal: 8, paddingTop: 2, paddingBottom: 9 },
  detailCardTitleWrap: {   marginBottom: 5, borderWidth: 1, borderColor: "#39d34a", borderRadius: 5, backgroundColor: "#c9f6c6",  paddingVertical: 6,marginTop:6 },
  detailCardTitle: { color: "#075416", fontSize: 16, lineHeight: 24, fontWeight: "900", textAlign: "center" },
  detailBullets: { gap: 2 },
  detailBulletRow: { flexDirection: "row", alignItems: "flex-start" },
  detailBulletDot: { width: 14, color: "#111", fontSize: 17, lineHeight: 18, fontWeight: "900" },
  detailBulletLead: { color: "#075416", fontWeight: "900" },
  detailBulletText: { flex: 1, color: "#111", fontSize: 12, lineHeight: 20, fontWeight: "700" }
});
